name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: acre-cli

    - uses: actions/checkout@v3
      with:
        name: acre-bdd/acre-test
        path: acre-test
    
    - name: install and initialize acre cli
      run: |
        python3 -m pip install acre-cli/
        acre init

    - name: build acre docker images
      run: acre build

    - name: run acre-tests
      run: |
        cd acre-test
        ls -la
        acre run --noterm features/
        
      


